# Generated by Django 4.0.1 on 2022-03-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('party_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('party_name', models.CharField(max_length=100)),
                ('party_logo', models.CharField(max_length=500)),
                ('candidate_name', models.CharField(blank=True, max_length=100)),
                ('candidate_profile_pic', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('uuid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('pincode', models.CharField(max_length=6)),
                ('region', models.CharField(max_length=100)),
                ('profile_pic', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('vote_done', models.BooleanField(default=False)),
            ],
        ),
    ]
