# Generated by Django 4.0.1 on 2022-03-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Voters',
            new_name='Voter',
        ),
    ]
