# Generated by Django 4.0.1 on 2022-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_rename_voters_voter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='uuid',
            new_name='Aadhar_no',
        ),
    ]
