# Generated by Django 3.2.5 on 2022-04-04 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_rename_uuid_voter_aadhar_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recmail', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
