# Generated by Django 3.2.5 on 2022-04-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_alter_varn_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time_Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('time', models.DateField()),
            ],
        ),
    ]
