# Generated by Django 3.2.5 on 2022-04-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0008_alter_time_num_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_num',
            name='an',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
