# Generated by Django 3.2.5 on 2022-04-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0009_time_num_an'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usrid', models.CharField(max_length=12)),
                ('Vid1', models.CharField(max_length=100)),
                ('Vid2', models.CharField(max_length=44)),
            ],
        ),
    ]
