# Generated by Django 4.0.1 on 2022-04-17 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0011_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecMail',
        ),
        migrations.DeleteModel(
            name='Varn',
        ),
    ]
