# Generated by Django 4.0.1 on 2022-04-17 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0013_remove_voter_profile_pic_voter_voter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politicalparty',
            name='candidate_profile_pic',
        ),
    ]
