# Generated by Django 4.0.1 on 2022-04-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0018_alter_voter_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
