# Generated by Django 4.0.1 on 2022-04-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0026_alter_result_pn_alter_voter_aadhar_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time_num',
            name='an',
        ),
    ]
