# Generated by Django 4.0.1 on 2022-04-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0027_remove_time_num_an'),
    ]

    operations = [
        migrations.AddField(
            model_name='time_num',
            name='an',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
