# Generated by Django 4.0.1 on 2022-04-28 08:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0028_time_num_an'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(default=datetime.date(2004, 4, 15)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='pincode',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6,6}$')]),
        ),
    ]
