# Generated by Django 4.0.1 on 2022-04-28 09:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0029_alter_voter_dob_alter_voter_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politicalparty',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(111947), django.core.validators.MaxValueValidator(112004)]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')]),
        ),
        migrations.AlterField(
            model_name='voter',
            name='region',
            field=models.CharField(choices=[('GJ', 'Gujarat'), ('MH', 'Maharashtra'), ('RJ', 'Rajasthan'), ('MP', 'Madhya Pradesh'), ('HR', 'Haryana')], default='GJ', max_length=2),
        ),
    ]
