# Generated by Django 4.0.1 on 2022-04-28 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0030_alter_politicalparty_candidate_name_alter_voter_dob_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(default=datetime.date(2004, 4, 15)),
        ),
    ]
