# Generated by Django 4.0.1 on 2022-04-28 09:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0031_alter_voter_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='dob',
        ),
        migrations.AddField(
            model_name='voter',
            name='date',
            field=models.IntegerField(max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
        migrations.AddField(
            model_name='voter',
            name='month',
            field=models.IntegerField(max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AddField(
            model_name='voter',
            name='year',
            field=models.IntegerField(max_length=2, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2004)]),
        ),
    ]
