# Generated by Django 4.0.1 on 2022-04-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0032_remove_voter_dob_voter_date_voter_month_voter_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='date',
            new_name='day',
        ),
    ]
