# Generated by Django 4.0.1 on 2022-04-28 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0033_rename_date_voter_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='name',
        ),
        migrations.AddField(
            model_name='voter',
            name='Firstname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')]),
        ),
        migrations.AddField(
            model_name='voter',
            name='Lastname',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$')]),
        ),
    ]
