# Generated by Django 4.0.1 on 2022-04-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0034_remove_voter_name_voter_firstname_voter_lastname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='Firstname',
            new_name='name',
        ),
    ]
