# Generated by Django 4.0.1 on 2022-04-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0035_rename_firstname_voter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='Lastname',
        ),
    ]
